version: "3"

services:
  hq:
    container_name: elastichq
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
     - "5000:5000"
    depends_on:
      - redis
  redis:
    build: ./deployment/redis
    container_name: redisdb
    expose:
      - "6379"
